### ISSUE TITLE
New technology

### ISSUE THREAD

**Issue by rhymeunder** [HawpT/BrainFloss#6]
Issue I found when trying to use Adobe Flash Builder

-could download creative cloud but not finish install on windows

**Comment by colettebedoya** [comment]
I was able to download it.  Did you try going in and doing an update on the software?  I had to do that for photoshop when I installed it on my new machine.

**Comment by HawpT** [comment]
Creative Cloud can't install Flash Builder? Strange. I will look at it tomorrow.
